application: makeeoinproud
version: 1
runtime: python
api_version: 1

default_expiration: "7d"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /.*
  script: makeeoinproud.py

